version: "2"

services:

  my-rabbit:
    container_name: my-rabbit
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/etc/rabbitmq
#    volumes:
#      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
#      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_NODENAME: my-rabbit

  producer:
    container_name: producer
    image: spabbit/producer
    ports:
     - "8080:8080"
    depends_on:
     - my-rabbit
         
  consumer:
    container_name: consumer
    image: spabbit/consumer
    depends_on:
     - my-rabbit
